# Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
os:
  - linux
  # - osx
julia:
  - 1

matrix:
  allow_failures:
  - julia: nightly

addons:
  apt:
    packages:
      - at-spi2-core
      - libgtk-3-dev
      - xauth
      - xvfb

sudo: required

notifications:
  email: false

before_install:
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys E084DAB9; fi
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then sudo add-apt-repository -y "deb http://cran.rstudio.com/bin/linux/ubuntu $(lsb_release -s -c)/"; fi
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then sudo apt-get update -qq -y; fi
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then sudo apt-get install --allow-unauthenticated git r-base r-base-dev r-recommended -y; fi

r_packages: RColorBrewer
r_github_packages: sahirbhatnagar/ggmix

#script:
#  - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
#  - if [[ `uname` = "Linux" ]]; then TESTCMD="xvfb-run julia"; else TESTCMD="julia"; fi
#  - $TESTCMD -e 'using Pkg; Pkg.build()'
