# Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia

os:
  - linux
  dist: bionic

julia:
  - 1

matrix:
  allow_failures:
  - julia: nightly

addons:
  - apt:
    packages:
      - at-spi2-core
      - libgtk-3-dev
      - xauth
      - xvfb

sudo: required

notifications:
  email: false

before_install:
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys E084DAB9; fi
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then sudo add-apt-repository -y "deb http://cran.rstudio.com/bin/linux/ubuntu $(lsb_release -s -c)/"; fi
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then sudo apt-get update -qq -y; fi
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then sudo apt-get install --allow-unauthenticated git r-base r-base-dev r-recommended -y; fi
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then mkdir ~/R_packages_test/; fi
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then echo -e 'R_LIBS=~/R_packages_test/' > ~/.Renviron; fi
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then Rscript -e "install.packages('RColorBrewer')"; fi
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then Rscript -e "install.packages('pacman'); pacman::p_load_gh('sahirbhatnagar/ggmix')" || echo "Cannot install ggmix in R"; fi
