# Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia

dist: 
  - bionic

julia:
  - 1

matrix:
  allow_failures:
  - julia: nightly

addons:
  - apt:
    packages:
      - at-spi2-core
      - libgtk-3-dev
      - xauth
      - xvfb

sudo: required

notifications:
  email: false

before_install:
  - sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys E298A3A825C0D65DFD57CBB651716619E084DAB9
  - sudo add-apt-repository 'deb https://cloud.r-project.org/bin/linux/ubuntu bionic-cran35/'
  - sudo apt-get update -qq -y
  - sudo apt-get install --allow-unauthenticated git r-base r-base-dev r-recommended -y
  - mkdir ~/R_packages_test/
  - echo -e 'R_LIBS=~/R_packages_test/' > ~/.Renviron
  - Rscript -e "install.packages('RColorBrewer')"
  - Rscript -e "install.packages('pacman'); pacman::p_load_gh('sahirbhatnagar/ggmix')" || echo "Cannot install ggmix in R"
