authors = ["jeffersonfparil <jeffersonparil@gmail.com>"]
name = "GWAlpha"
uuid = "db0974fc-fbd1-11e9-101e-a1a1bca81ff8"
version = "0.1.0"
repository = "https://github.com/jeffersonfparil/GWAlpha"
description = "Genome-wide estimate of genetic effects for genome-wide association and genomic prediction of quantitative traits from pool sequencing data. This repository also include landscape simulations."
keywords = "GWAS, GP, genomic prediction, genomic selection, genome-wide association, Pool-seq, pool sequencing, simulation, landscape, quantinemo, npstat, julia"

[deps]
Pkg = “44cfe95a-1eb2-52ea-b672-e2afdf69b78f”
DelimitedFiles = "8bb1440f-4735-579b-a4ab-409b98df4dab"
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Optim = "429524aa-4258-5aef-a3af-852621145aeb"
GLMNet = "8d5ece8b-de18-5317-b113-243142960cc6"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
ProgressMeter = "92933f4c-e287-5a05-a399-4b506db050ca"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
ColorBrewer = "a2cac450-b92f-5266-8821-25eda20663c8"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
RCall = "6f49c342-dc21-5d91-9882-a32aef131414"

